apiVersion: v1
kind: Service
metadata:
  name: redfish-event-listener
  namespace: default
  labels:
    app: redfish-event-listener
spec:
  type: ClusterIP
  selector:
    app: redfish-event-listener
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
